### ISSUE TITLE
[Question] Compatibility of Enttec DMX USB Pro MK2 Interface

### ISSUE THREAD

**Issue by hrueger** [node-dmx/dmx#102]
Does anybody know if the `Enttec DMX USB Pro MK2 Interface` has the same chip as the older `Enttec USB DMX Pro` model? Is it compatible with this library?

**Comment by wiedi** [comment]
Had a quick look at the example code provided by Enttec and most of the constants look the same.
So while I have not tested it myself I'd expect it to either work out of the box or at least be easy to add support for it if it doesn't.

**Comment by hrueger** [comment]
Thanks!

**Comment by hrueger** [comment]
I just tried it out, it works perfectly.
