### ISSUE TITLE
Fade curves.

### ISSUE THREAD

**Issue by XanderCodes** [node-dmx/dmx#106]
Hey there!

I have a basic fade in - fade out animation running with this library on my (DIY) Enttec Open DMX controller, connected to two Chauvet SlimPars.

The problem I am running into is that the animation seems to be super choppy, as in, you can see the fixture switching intensity levels in steps, and it doesn't appear smooth. I have tried multiple of the "easing" options but haven't really felt any of them improved the fixture's output.

I know the problem is not my adapter, or the fixtures, as running the same setup through QLC+ (free open-source lighting software), the fade times are a lot smoother.

I don't know if it's a matter of the framerate of this library or its animation feature, but any help is certainly appreciated!

**Comment by simonbuehler** [comment]
@XanderCodes hi, how did it resolve?
