### ISSUE TITLE
ENTTEC buffer bierfly resets to 0 

### ISSUE THREAD

**Issue by Nubebuster** [node-dmx/dmx#150]
ENTTEC buffer bierfly resets to 0 when simply sending an update. I don't know exactly what causes this. It could be that when updating (at 44Hz) the values are messed up. Is there some way to disable the resend or change the interval?

**Comment by wiedi** [comment]
Is that with the "open" or the "pro"?

**Comment by Nubebuster** [comment]
ODE MK2 ethernet

**Comment by Nubebuster** [comment]
Setting dmx speed to 0 like this

`universe = dmx.addUniverse("test", "artnet", enttecip.value, {
        dmx_speed: 1,
      });`

Fixes the issue seemingly. But doesn't fix the actual problem

**Comment by Nubebuster** [comment]
The best solution would be to be able to configure to only send an update when values have changed. This would still not fix the actual issue though. This could mean that when you do change values, the values in the ENTTEC are still reset to 0 briefly

**Comment by Nubebuster** [comment]
Solved. I was accessing the universe singleton instance I made with async calls without locking the initializations. This would end up with one universe instance sending 0 values. The other sending my values.
