### ISSUE TITLE
Which driver for Eurolite USB-DMX512 Interface?

### ISSUE THREAD

**Issue by ilouHD** [node-dmx/dmx#45]
Can I use one of the preset drivers for an Eurolite USB-DMX512 Interface or do I have to find/develop a new one?

**Comment by dreammonkey** [comment]
To my findings the Eurolite usb dmx512 pro mk2 works using the enttec-usb-dmx-pro driver.
No modifications needed. I tested on Mac and Linux.

**Comment by ilouHD** [comment]
Thank you for testing, but the problem is, in our school we only have the "normal" version of the interface, not the Pro (mk2).
But maybe this works as well. I think I test it out, when I'm in school next time.

**Comment by wiedi** [comment]
Thanks for confirming @maniflames. Sounds like this issue is resolved then.

If there are further questions feel free to reopen.
