### ISSUE TITLE
How to configure the driver on windows?

### ISSUE THREAD

**Issue by fralbo** [node-dmx/dmx#56]
hello,

Looking at the config file, I'm wondering how to specify the driver access point on Win 10?

BR,
Alain

**Comment by bluemaex** [comment]
@fralbo Sorry I can't really help you here as I do not have a  Windows machine to test on, but as far as I remember the SerialPort are called something like COM2, COM3 etc.

We use the nodejs package ``serialport`` which has support for windows and I found this gist which might help you testing it: https://gist.github.com/maximilian-lindsey/b5a981d3657627bfbb89
If you suceed please let us know, then we update the documentation!

Cheers
Max

**Comment by fralbo** [comment]
Yes, I suppose it should be as simple. 
I'm waiting for the device. I'll let you know ASAP.

**Comment by apsylone** [comment]
@fralbo I've you found a solution to this ? :-) 

Thanks,

**Comment by bluemaex** [comment]
I guess this issue got resolved due to no response in the last 4 months - Feel free to reopen it if there are still questions!

**Comment by sebbean** [comment]
what's the solution?

**Comment by apsylone** [comment]
@sebbean try to use COM1, COM2... as @bluemaex mentionned :-)

**Comment by gabrielstuff** [comment]
Hello, 

I'm starting to try `dmx-web` on windows. So far, I'm happy. You can check here https://gist.github.com/gabrielstuff/bb3b69926c32cf5164467b1a45fc7c47 how to do. Basically, you look at your serial settings and find what is the `COM` : `COM1`, `COM2`, `COM3`, `COM4`, `COM5`

It should show as `Serial USB (COMX)`
