### ISSUE TITLE
A few small questions

### ISSUE THREAD

**Issue by aussie-katie** [node-dmx/dmx#77]
I have a few questions before I am going to get into this
- To use this with a DMX lighting system I would need a USB to DMX interface then I would set the connection port in my JS file
- Could I use this in an Electron app, and I would do this I would set up some controls and have those written to a variable then parse that into the DMX library
- Does this library have all the capabilities of a prebuilt software like *ShowXpress*  I just need to make it usable

Thank you

**Comment by Fensterbank** [comment]
> To use this with a DMX lighting system I would need a USB to DMX interface then I would set the connection port in my JS file

Yes. ENTTEC DMX USB Pro with this library.

> Could I use this in an Electron app, and I would do this I would set up some controls and have those written to a variable then parse that into the DMX library

Yes of course. That's the reason why it is a library which can be used standalone.
You can easily call the library methods directly from your electron app.

> Does this library have all the capabilities of a prebuilt software like _ShowXpress_  I just need to make it usable

I don't know this software, but I would say no.

**Comment by Griffdith** [comment]
Thank you, but for the interface do I *need* to use that interface, or is that the only one guaranteed to work?

**Comment by Griffdith** [comment]
> Regarding electron: there is already one project using it: https://davidhoare.net/easycue/index.html - so you could get inspiration or how is used from there :)

Thank you for that, but that is for Mac only and to be perfectly honest I sorta want a fun project to do and it might be helpful.

**Comment by Fensterbank** [comment]
> Thank you, but for the interface do I _need_ to use that interface...

Sorry, I somehow removed a part of my sentence when copying the product name. 😅
For my use cases I use ENTTEC DMX USB Pro which works fine and out of the box.
But more devices are supported by this library, see this driver folder: https://github.com/node-dmx/dmx/tree/master/drivers
Technically it's no rocket science so it should be easy to add more drivers for other DMX usb converters...

I would refrain from using the much cheaper ENTTEC Open USB DMX, it did not work for me and as I read it doesn't have an internal clocking thing so it's kind of dependent of the computer if it works or not.

**Comment by Griffdith** [comment]
> Technically it's no rocket science so it should be easy to add more drivers for other DMX USB converters...

So if I could be bothered I could obtain the drivers that get installed with my interface, then place them into that folder and it *might* work?

**Comment by Griffdith** [comment]
Actually, nevermind looks much more complicated...

**Comment by bluemaex** [comment]
> Thank you, but for the interface do I _need_ to use that interface, or is that the only one guaranteed to work?

No you do absolutely not need to use that interface. The Interface is very very simple and is just an example  how you can use the API that the library exposes. It is just a demonstration :)

> So if I could be bothered I could obtain the drivers that get installed with my interface, then place them into that folder and it _might_ work?

No - If you use an yet unsupported device - you (or someone) needs to write a driver to control the device. then you can use it inside this library. Out of curiosity which device do you use/want to use?

> Thank you for that, but that is for Mac only and to be perfectly honest I sorta want a fun project to do and it might be helpful.

If you checkout the sources and build your own version it will also work on Linux and Windows. :-)

**Comment by Griffdith** [comment]
> No - If you use an yet unsupported device - you (or someone) needs to write a driver to control the device. then you can use it inside this library. Out of curiosity which device do you use/want to use?

My project is just a hobby, the DMX software my school uses is a bit crappy and I wanted to build my own, and I think my school uses [this](https://www.chauvetdj.com/products/xpress-512/) one.

**Comment by Griffdith** [comment]
So how would I go about writing a driver for a new interface @Fensterbank

**Comment by williamoverton** [comment]
@Griffdith You would have to find the datasheet for the device and write a new driver in the drivers folder (look at the drivers currently included for examples) First things first, check what device your school is currently using as it might be compatible with another device that there is a driver for.

**Comment by Griffdith** [comment]
I know what device my school is using, it's the *Xpress 512*. Where would I find this *datasheet*, @williamoverton?

**Comment by jasonappah** [comment]
@Griffdith, I realize this is an old issue, but the ShowXpress interfaces are unable to communicate with any other programs. I think I recall seeing some workaround somewhere which allowed the ShowXpress software to receive ArtNet in, which this library can send.

**Comment by Griffdith** [comment]
Oh, course they don't work with anything else, why would they want to do that.

**Comment by ParthuP** [comment]
Hello Guys,

Today i started using dmx library and when i tried to perform some animation it says easing is undefined at line number 64 inside Anim.js file. Not sure whether i have latest library or this is existing bug.

Could you please confirm.

code snippet fyi:

easing(ticks, 0, 1, duration)

Regads,
Parthu P.
