### ISSUE TITLE
Multiple DMX512 Decoders

### ISSUE THREAD

**Issue by cc-greglorenzen** [node-dmx/dmx#82]
This may be a question more related to how DMX works in general, rather than how the library works, so I apologize if that's the case, but how do the channel numbers work when using multiple DMX decoders daisy chained together? Do they just increment until the max 512 channels are reached?

**Comment by wiedi** [comment]
You assign each device (decoder?) an address (channel) on the bus. This is often done using dip-switches or small buttons.

You can assign multiple devices to the same channel and they will behave the same way. Some devices can use more than one channel (for example three channels for red, green, blue) so you have to take care that these don't overlap.

The channel assignment is independent of the cabeling or the order in which the devices are placed on the bus.

The channel is just the byte position in the channel data of the DMX frame. So if your decoder wants to know what value channel 7 has it will just look at the 7th position.

I hope this is an answer to what you're asking.
