### ISSUE TITLE
Upgrade serialport dependency for Node v12

### ISSUE THREAD

**Issue by foxxyz** [node-dmx/dmx#86]
As documented here (https://github.com/serialport/node-serialport/issues/1905), the currently pinned version of serialport (6.0.4) no longer compiles using Node v12 and makes it so `dmx` cannot be installed.

[Versions 7 and 8 do compile on Node v12](https://github.com/serialport/node-serialport/issues/1905#issuecomment-521367237), so a dependency upgrade would probably fix it.

OS: MacOS
Node version: 12.8.0
CPU: 3.1Ghz Intel i7

**Comment by foxxyz** [comment]
@Fensterbank any chance of accepting #87?

**Comment by Fensterbank** [comment]
Yup. Thanks for the mention. :)

**Comment by Fensterbank** [comment]
PR #87 was merged and the issue is resolved.
